# Generated by Django 4.1 on 2022-08-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0003_heroes_heroe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroes',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heroes',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
