# Generated by Django 4.1 on 2022-08-25 11:55

from django.db import migrations, models
import heroes.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('id_heroe', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rank', models.CharField(max_length=1)),
                ('position', models.IntegerField()),
                ('race', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=1)),
                ('photo', models.ImageField(blank=True, max_length=254, null=True, upload_to=heroes.models.heroeFile)),
            ],
        ),
    ]
