# Generated by Django 4.1 on 2022-08-26 11:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id_rank', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.CharField(max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='heroes',
            name='rank',
        ),
        migrations.AddField(
            model_name='heroes',
            name='fk_rank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='heroes.rank'),
            preserve_default=False,
        ),
    ]
