# Generated by Django 4.1 on 2022-08-26 11:33

from django.db import migrations, models
import stdimage.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('id_heroe', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rank', models.CharField(max_length=1)),
                ('position', models.IntegerField()),
                ('race', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=1)),
                ('photo', stdimage.models.StdImageField(force_min_size=False, upload_to='%y/%m/%d', variations={})),
            ],
        ),
    ]
