# Generated by Django 4.1 on 2022-08-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_rank_remove_heroes_rank_heroes_fk_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroes',
            name='heroe_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
